service: apigw-twitter-clone

provider:
  name: aws
  runtime: nodejs12.x
  project: apigt-twitter-clone
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  apiName: apigw-${self:provider.stage}
  memorySize: 128
  environment:
    NODE_ENV: ${self:provider.stage}

custom:
  prefix-name: ${self:service}-${self:provider.stage}

functions:
  gateway:
    name: ${self:custom.prefix-name}
    handler: dist/main-aws.handler
    timeout: 30
    events:
      - http:
          path: /{any+}
          method: any
    package:
      include:
        - dist/**
    tags:
      project: apigw
      environment: ${self:provider.stage}
